### ISSUE TITLE
margin-left: auto; margin-right: auto;

### ISSUE THREAD

**Issue by chrisbuttery** [tachyons-css/tachyons-spacing#8]
What are your thoughts on including something like this in the project?

``` css
.mh-auto {
  margin-right: auto;
  margin-left: auto;
}
```

This class is something I use in my projects alongside `tachyons-spacing`, when horizontally centering elements.
